
server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/identity_service"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      generate-ddl: true
jwt:
  signerKey: "YYMSGFkeMQ27FMb6k4EwDCpAAytQAPJ57vjmLq7TYm6e/4Scd8bYrsu9s2anrf6j"